_core:
  default_config_hash: Nh2kBYOQBgZ8cyaqvf8VJKnC1gR_rxFsVy-51w7PJkw
default_case: standard
enable_attributes: true
enable_auto_complete: true
enable_id_replacement: true
enable_special_chars: false
field_type: multiple_textfields
filter_html_clean_css_identifier: false
items_per_page: 50
qty_attributes_per_block: 10
qty_classes_per_block: 10
maxlength_attributes: false
maxlength_block_class_field: 255
maxlength_id: 255
weight_attributes: ''
weight_class: ''
weight_id: ''
block_classes_stored: '{"":""}'
