_core:
  default_config_hash: R4IF-ClDHXxblLcG0L7MgsLvfBIMAvi_skumNFQwkDc
module:
  address: 0
  admin_toolbar: 0
  admin_toolbar_tools: 0
  automated_cron: 0
  back_to_top: 0
  backup_migrate: 0
  big_pipe: 0
  block: 0
  block_class: 0
  block_content: 0
  breakpoint: 0
  ckeditor: 0
  config: 0
  contextual: 0
  crop: 0
  ctools: 0
  datetime: 0
  datetime_range: 0
  dblog: 0
  devel: 0
  devel_generate: 0
  devel_kint_extras: 0
  dynamic_page_cache: 0
  editor: 0
  entity_browser: 0
  entity_reference_revisions: 0
  entityqueue: 0
  field: 0
  field_group: 0
  field_ui: 0
  file: 0
  filter: 0
  focal_point: 0
  fontawesome: 0
  fontawesome_iconpicker_widget: 0
  help: 0
  history: 0
  honeypot: 0
  image: 0
  image_widget_crop: 0
  imce: 0
  jquery_ui: 0
  jquery_ui_accordion: 0
  jquery_ui_effects: 0
  link: 0
  link_attributes: 0
  menu_link_attributes: 0
  menu_link_content: 0
  menu_ui: 0
  metatag: 0
  metatag_facebook: 0
  metatag_twitter_cards: 0
  mysql: 0
  node: 0
  node_view_permissions: 0
  options: 0
  page_cache: 0
  path: 0
  path_alias: 0
  permissions_filter: 0
  redirect: 0
  responsive_image: 0
  responsive_menu: 0
  search: 0
  shortcut: 0
  simple_sitemap: 0
  simple_styleguide: 0
  super_login: 0
  system: 0
  taxonomy: 0
  taxonomy_manager: 0
  telephone: 0
  telephone_validation: 0
  term_reference_tree: 0
  text: 0
  token: 0
  toolbar: 0
  twig_tweak: 0
  update: 0
  user: 0
  views_accordion: 0
  views_ui: 0
  viewsreference: 0
  we_megamenu: 0
  webform: 0
  webform_ui: 0
  extlink: 1
  pathauto: 1
  views: 10
  paragraphs: 11
  standard: 1000
theme:
  seven: 0
  adminimal_theme: 0
  bootstrap_barrio_d9: 0
  bootstrap_barrio: 0
  nis: 0
profile: standard
