features:
  node_user_picture: 1
  comment_user_picture: true
  comment_user_verification: true
  favicon: 1
logo:
  use_default: 0
  path: 'public://logo.png'
favicon:
  use_default: 0
  path: 'public://favicon.ico'
  mimetype: image/vnd.microsoft.icon
bootstrap_barrio_source: '0'
bootstrap_barrio_fluid_container: 0
bootstrap_barrio_region_clean_custom_search: 0
bootstrap_barrio_region_class_custom_search: row
bootstrap_barrio_region_clean_pre_header: 0
bootstrap_barrio_region_class_pre_header: row
bootstrap_barrio_region_clean_header: 1
bootstrap_barrio_region_class_header: ''
bootstrap_barrio_region_clean_hero: 0
bootstrap_barrio_region_class_hero: row
bootstrap_barrio_region_clean_content: 1
bootstrap_barrio_region_class_content: ''
bootstrap_barrio_region_clean_sidebar: 0
bootstrap_barrio_region_class_sidebar: row
bootstrap_barrio_region_clean_pre_footer: 0
bootstrap_barrio_region_class_pre_footer: row
bootstrap_barrio_region_clean_footer: 0
bootstrap_barrio_region_class_footer: row
bootstrap_barrio_sidebar_position: left
bootstrap_barrio_content_offset: '0'
bootstrap_barrio_sidebar_collapse: 0
bootstrap_barrio_sidebar_first_width: '2'
bootstrap_barrio_sidebar_first_offset: '0'
bootstrap_barrio_sidebar_second_width: '2'
bootstrap_barrio_sidebar_second_offset: '0'
bootstrap_barrio_hide_node_label: 0
bootstrap_barrio_button: 0
bootstrap_barrio_button_size: ''
bootstrap_barrio_button_outline: 0
bootstrap_barrio_image_fluid: 0
bootstrap_barrio_navbar_container: 0
bootstrap_barrio_navbar_toggle: navbar-toggleable-xl
bootstrap_barrio_navbar_top_navbar: 0
bootstrap_barrio_navbar_top_position: ''
bootstrap_barrio_navbar_top_color: ''
bootstrap_barrio_navbar_top_background: ''
bootstrap_barrio_navbar_position: ''
bootstrap_barrio_navbar_color: ''
bootstrap_barrio_navbar_background: ''
bootstrap_barrio_navbar_top_class: ''
bootstrap_barrio_navbar_class: ''
bootstrap_barrio_navbar_offcanvas: ''
bootstrap_barrio_navbar_flyout: 0
bootstrap_barrio_navbar_slide: 0
bootstrap_barrio_tabs_style: ''
bootstrap_barrio_messages_widget: default
bootstrap_barrio_navbar_top_affix: 0
bootstrap_barrio_navbar_affix: 0
bootstrap_barrio_sidebar_first_affix: 0
bootstrap_barrio_sidebar_second_affix: 0
bootstrap_barrio_scroll_spy: ''
bootstrap_barrio_google_fonts: ''
bootstrap_barrio_bootstrap_icons: 0
bootstrap_barrio_icons: ''
bootstrap_barrio_system_messages: ''
bootstrap_barrio_table_style: ''
bootstrap_barrio_table_hover: 0
bootstrap_barrio_table_head: ''
